### ISSUE TITLE
Overall public consultation start and end dates?

### ISSUE THREAD

**Issue by camfindlay** [bcgov/openconsult#7]
I notice in the core requirements there is no generate start and end date to define the timebox that the consultation is open for.

Yes there will be certain public events etc withing a consultation however the overall time period for feedback etc in practice is usually set in advance (and sometime even before any documents and events are set).

Was the intention to use the core dataset level "PublicEventStartDate" and "PublicEventEndDate" to deal with this?

Thanks! :)

**Comment by tbcuthbert** [comment]
Hi Cam,

I can connect you with Jason at PlaceSpeak to follow-up on this if you like.

Bruce

**Comment by camfindlay** [comment]
@tbcuthbert yes please!

**Comment by hughstimson** [comment]
Hi @camfindlay, yes I think the thinking was that the "start" and "end" date of a consultation process would presumably be substantively defined by the public's ability to submit to it, and therefore by the start and end date of the public event components of the consultation.

The only issue I can see with adding a global start and end date to a consultation is that those could inadvertently be set to start later or end earlier than the public events, which would be an ambiguous to interpret.

But I don't suppose that's a big danger. If folks thought global start/end dates were useful then probably they should be.

**Comment by camfindlay** [comment]
All good, I think as it stands we'll make use of the core PublicEvent start and end dates it works and doesn't introduce extra date fields.
